In [98]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [137]:
df1 = pd.read_csv("Candidate_Test_Main.csv",sep=';')
df1.set_index('SubscID', inplace=True)
df1.head()

,Amount,AmountRange,Decision,Company,Age,Tobacco,WeightBmi,BpSystolic,BpDiastolic,Cholesterol
SubscID,,,,,,,,,,
0,250000.0,C 100k1 to 250k,Rated,G,47,Non-Smoker,38.74,126.0,82.0,186.0
1,150000.0,C 100k1 to 250k,Decline,B,28,Smoker,NaN,NaN,NaN,NaN
2,4500000.0,F 1M1 to 5M,Decline,E,61,Non-Smoker,23.71,120.0,68.0,152.0
3,25000.0,A to 50k,Decline,E,16,Non-Smoker,NaN,NaN,NaN,NaN
4,1000000.0,E 500k1 to 1M,Standard,F,28,Non-Smoker,28.72,110.0,71.0,194.0

In [138]:
df1.shape

(1235, 10)

Q1 : Import both datasets and describe them. At first glance, which comments can you make on the datasets?
I see that:
- dependent variable is Decision 
- independent variable is other
- index variable is SubscID
- the missing value is in the type continuos, so i decide to replace by the mean to keep the distribution 
- to handle the categorical data I will use the one hot encoder

In [139]:
df1.describe()

,Amount,Age,WeightBmi,BpSystolic,BpDiastolic,Cholesterol
count,1.235000e+03,1235.000000,1022.000000,958.000000,958.000000,890.000000
mean,9.707247e+05,43.085020,30.000391,121.093946,77.501044,190.970787
std,2.388104e+06,12.176247,6.735894,12.835001,9.099330,41.372369
min,0.000000e+00,0.000000,15.430000,90.000000,53.000000,78.000000
25%,2.550005e+05,34.000000,25.150000,112.000000,71.000000,162.250000
50%,5.000000e+05,42.000000,28.790000,120.000000,78.000000,189.000000
75%,1.000000e+06,52.000000,33.445000,129.000000,82.750000,217.750000
max,4.800000e+07,78.000000,56.410000,175.000000,116.000000,400.000000

In [140]:
df2 = pd.read_csv("Candidate_Test_Sub.csv",sep=';')
df2.head()

   SubscID  DiseaseCode
0      116           36
1      682            6
2      115          379
3      264           19
4      321          152

Q2: Combine both datasets. Which comments can you make?

I use a left join to join two data set because in data set 1 there are many dominant feature, and in data set 2 just 1 feature supplementaire.

In [141]:
join_df = df1.join(df2.set_index('SubscID'))
join_df.head()

,Amount,AmountRange,Decision,Company,Age,Tobacco,WeightBmi,BpSystolic,BpDiastolic,Cholesterol,DiseaseCode
SubscID,,,,,,,,,,,
0,250000.0,C 100k1 to 250k,Rated,G,47,Non-Smoker,38.74,126.0,82.0,186.0,NaN
1,150000.0,C 100k1 to 250k,Decline,B,28,Smoker,NaN,NaN,NaN,NaN,153.0
2,4500000.0,F 1M1 to 5M,Decline,E,61,Non-Smoker,23.71,120.0,68.0,152.0,NaN
3,25000.0,A to 50k,Decline,E,16,Non-Smoker,NaN,NaN,NaN,NaN,290.0
3,25000.0,A to 50k,Decline,E,16,Non-Smoker,NaN,NaN,NaN,NaN,319.0

In [142]:
join_df['AmountRange'] = join_df['AmountRange'].astype(str).str[0]

In [143]:
join_df.head()

,Amount,AmountRange,Decision,Company,Age,Tobacco,WeightBmi,BpSystolic,BpDiastolic,Cholesterol,DiseaseCode
SubscID,,,,,,,,,,,
0,250000.0,C,Rated,G,47,Non-Smoker,38.74,126.0,82.0,186.0,NaN
1,150000.0,C,Decline,B,28,Smoker,NaN,NaN,NaN,NaN,153.0
2,4500000.0,F,Decline,E,61,Non-Smoker,23.71,120.0,68.0,152.0,NaN
3,25000.0,A,Decline,E,16,Non-Smoker,NaN,NaN,NaN,NaN,290.0
3,25000.0,A,Decline,E,16,Non-Smoker,NaN,NaN,NaN,NaN,319.0

Q3 : Run some statistical analysis on the dataset and interpret them.

Q4: The business is interested in predicting the Decision. Determine which features seem relevant prior to modeling it, using the method you want.

In [147]:
target = join_df['Decision']
drop_target_df = join_df.drop(['Decision'],axis = 1)
#df_dummies = pd.get_dummies(drop_target_df)
df_dummies = pd.get_dummies(join_df)

In [148]:
df_dummies.iloc[:,0 : 40].head()

,Amount,Age,WeightBmi,BpSystolic,BpDiastolic,Cholesterol,DiseaseCode,AmountRange_A,AmountRange_B,AmountRange_C,...,Company_B,Company_C,Company_D,Company_E,Company_F,Company_G,Tobacco_Non-Smoker,Tobacco_Occasional,Tobacco_Smoker,Tobacco_Unknown
SubscID,,,,,,,,,,,,,,,,,,,,,
0,250000.0,47,38.74,126.0,82.0,186.0,NaN,0,0,1,...,0,0,0,0,0,1,1,0,0,0
1,150000.0,28,NaN,NaN,NaN,NaN,153.0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
2,4500000.0,61,23.71,120.0,68.0,152.0,NaN,0,0,0,...,0,0,0,1,0,0,1,0,0,0
3,25000.0,16,NaN,NaN,NaN,NaN,290.0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
3,25000.0,16,NaN,NaN,NaN,NaN,319.0,1,0,0,...,0,0,0,1,0,0,1,0,0,0

In [155]:
df_dummies.fillna(df_dummies.mean(), inplace=True) # we decide to fillna by a mean value to keep a distribution

In [159]:
z = df_dummies.corr()

By the correlation, we decide to get feature which is most relevant with value of prediction which we want

In [188]:
a = z['Decision_Decline'].sort_values(ascending=False)[1:10]

In [223]:
col_Dec = a.index
col_Dec

Index(['Company_E', 'AmountRange_B', 'Amount', 'AmountRange_G', 'Company_C',
       'Tobacco_Unknown', 'Tobacco_Smoker', 'AmountRange_F', 'AmountRange_A'],
      dtype='object')

In [224]:
b = z['Decision_Standard'].sort_values(ascending=False)[1:10]
Col_Standard = b.index
Col_Standard

Index(['Company_B', 'Company_F', 'DiseaseCode', 'AmountRange_E',
       'AmountRange_C', 'Company_G', 'Tobacco_Occasional', 'Company_A',
       'Tobacco_Smoker'],
      dtype='object')

In [225]:
c = z['Decision_Rated'].sort_values(ascending=False)[1:10] 
col_Rated = c.index
col_Rated

Index(['Company_D', 'BpDiastolic', 'BpSystolic', 'WeightBmi',
       'Tobacco_Non-Smoker', 'Company_G', 'Age', 'AmountRange_A',
       'AmountRange_D'],
      dtype='object')

We decide to predict Decision by three model. Each model we take 9 feature which is most relevant feature.

Q5: Transform the dataset so that you can build a model on it.

We transform our model to binary classification. First, we apply the logistic classification

Model for Decision_Decline

In [215]:
train_test_df = df_dummies[col_Dec]
y = df_dummies['Decision_Decline'].values
#train_test_df = df_dummies[col_Rated]
#y = df_dummies['Decision_Rated'].values
#train_test_df = df_dummies[Col_Standard]
#y = df_dummies[''Decision_Standard''].values

In [218]:
from sklearn.model_selection import StratifiedShuffleSplit 

seed = 10
ssplit = StratifiedShuffleSplit(train_size=0.7, random_state=seed)
train_indices, test_indices = next(ssplit.split(train_test_df.values, y))

X_train = train_test_df.values[train_indices]
y_train = y[train_indices]
X_test = train_test_df.values[test_indices]
y_test = y[test_indices]

D:\python\lib\site-packages\sklearn\model_selection\_split.py:1788: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [219]:
from sklearn.linear_model import LogisticRegressionCV
log_reg_cv = LogisticRegressionCV(scoring='roc_auc', random_state=seed, 
                                  solver='liblinear', penalty='l2', 
                                  cv=5, n_jobs=10)
log_reg_cv.fit(X_train, y_train)

from sklearn.metrics import roc_auc_score, accuracy_score

y_test_preds = log_reg_cv.predict(X_test)
"AUC:", roc_auc_score(y_test, y_test_preds), "Accuracy:", accuracy_score(y_test, y_test_preds)

('AUC:', 0.49264705882352944, 'Accuracy:', 0.4589041095890411)

In [220]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


rf = RandomForestClassifier(random_state=seed)

max_depth_values = range(5, 10)
n_estimators_values = range(10, 20, 2)
tree_params = {'max_depth': max_depth_values,
               'n_estimators': n_estimators_values}

gs = GridSearchCV(rf, tree_params, scoring='roc_auc', cv=5, n_jobs=10)
gs.fit(X_train, y_train)
gs.best_params_, gs.best_score_, gs.cv_results_['std_test_score'][gs.best_index_]

({'max_depth': 6, 'n_estimators': 10}, 0.6408587351548369, 0.03180913913036059)

In [221]:
rf = RandomForestClassifier(random_state=seed, **gs.best_params_)
rf.fit(X_train, y_train)

y_test_preds = rf.predict(X_test)
"AUC:", roc_auc_score(y_test, y_test_preds), "Accuracy:", accuracy_score(y_test, y_test_preds)

('AUC:', 0.6317873303167421, 'Accuracy:', 0.6438356164383562)

Q7:	How would you validate the results? And improve them? 
To improve, we decide to apply other method to find the best method

In [222]:
from sklearn.metrics import auc
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import precision_score
import time
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier
kf = KFold(n_splits=5, shuffle=True, random_state=0)
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier

def run_classifiers(clfs, X , Y): 
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
    for i in clfs:
        clf = clfs[i]
        cv_acc = cross_val_score(clf, X, Y, cv=kf)
        start_time = time.time()
        print(i)
        clf.fit(X_train, Y_train)
        Y_predict = clf.predict(X_test)
        print("La precision: ", precision_score(Y_test, Y_predict)*100, "%")
        print(classification_report(Y_test,  Y_predict))
        print("Time d'execution: %s seconds ---" % (time.time() - start_time))

clfs1 = {
'Bagging': BaggingClassifier(n_estimators=50),
'Adaboost': AdaBoostClassifier(n_estimators=50, random_state=1),
'Neural Network':MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1),
'GradientBoosting' :GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0),
'LG': LogisticRegressionCV(scoring='roc_auc', solver='liblinear', penalty='l2', cv=5, n_jobs=10),
'Random Forrest':  RandomForestClassifier(max_depth=9, n_estimators=18)
}
run_classifiers(clfs1, train_test_df.values,y)

Bagging
La precision:  61.25000000000001 %
              precision    recall  f1-score   support

           0       0.61      0.76      0.68       259
           1       0.61      0.44      0.51       223

   micro avg       0.61      0.61      0.61       482
   macro avg       0.61      0.60      0.59       482
weighted avg       0.61      0.61      0.60       482

Time d'execution: 0.05385565757751465 seconds ---
Adaboost
La precision:  65.0 %
              precision    recall  f1-score   support

           0       0.61      0.81      0.70       259
           1       0.65      0.41      0.50       223

   micro avg       0.62      0.62      0.62       482
   macro avg       0.63      0.61      0.60       482
weighted avg       0.63      0.62      0.61       482

Time d'execution: 0.049834251403808594 seconds ---
Neural Network
La precision:  0.0 %
              precision    recall  f1-score   support

           0       0.54      1.00      0.70       259
           1       0.00      0.00      0.00       223

   micro avg       0.54      0.54      0.54       482
   macro avg       0.27      0.50      0.35       482
weighted avg       0.29      0.54      0.38       482

Time d'execution: 0.014948606491088867 seconds ---

D:\python\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
D:\python\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
D:\python\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
D:\python\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

GradientBoosting
La precision:  65.03496503496503 %
              precision    recall  f1-score   support

           0       0.62      0.81      0.70       259
           1       0.65      0.42      0.51       223

   micro avg       0.63      0.63      0.63       482
   macro avg       0.63      0.61      0.60       482
weighted avg       0.63      0.63      0.61       482

Time d'execution: 0.03789973258972168 seconds ---

D:\python\lib\site-packages\sklearn\linear_model\logistic.py:1920: ChangedBehaviorWarning: The long-standing behavior to use the accuracy score has changed. The scoring parameter is now used. This warning will disappear in version 0.22.
  ChangedBehaviorWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:1920: ChangedBehaviorWarning: The long-standing behavior to use the accuracy score has changed. The scoring parameter is now used. This warning will disappear in version 0.22.
  ChangedBehaviorWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:1920: ChangedBehaviorWarning: The long-standing behavior to use the accuracy score has changed. The scoring parameter is now used. This warning will disappear in version 0.22.
  ChangedBehaviorWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:1920: ChangedBehaviorWarning: The long-standing behavior to use the accuracy score has changed. The scoring parameter is now used. This warning will disappear in version 0.22.
  ChangedBehaviorWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:1920: ChangedBehaviorWarning: The long-standing behavior to use the accuracy score has changed. The scoring parameter is now used. This warning will disappear in version 0.22.
  ChangedBehaviorWarning)

LG
La precision:  46.15384615384615 %
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       259
           1       0.46      1.00      0.63       223

   micro avg       0.46      0.46      0.46       482
   macro avg       0.23      0.50      0.32       482
weighted avg       0.21      0.46      0.29       482

Time d'execution: 0.03789806365966797 seconds ---
Random Forrest
La precision:  64.62585034013605 %
              precision    recall  f1-score   support

           0       0.62      0.80      0.70       259
           1       0.65      0.43      0.51       223

   micro avg       0.63      0.63      0.63       482
   macro avg       0.63      0.61      0.61       482
weighted avg       0.63      0.63      0.61       482

Time d'execution: 0.02000594139099121 seconds ---

To predict other value of Decision, we can change the data.